- name: Update Apt Cache (Ubuntu)
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update Yum Cache (Other OS)
  yum:
    update_cache: yes
  when: ansible_distribution == "Centos" or ansible_distribution == "Amazon"
  