- include_role:
    name: cache_update

- name: Install SQLite for Ubuntu
  apt: 
    name: sqlite3
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install SQLite for Centos
  yum: 
    name: sqlite3
    state: present
  when: ansible_distribution == "Centos"

- name: Install SQLite (Amazon)
  dnf:
    name: sqlite
    state: present
  when: ansible_distribution == "Amazon"